import { MODULE_NAME } from './constants'

export const ADD_ITEM_TO_LIST = `${MODULE_NAME}/ADD_ITEM_TO_LIST`
export const REMOVE_ITEM_FROM_LIST = `${MODULE_NAME}/REMOVE_ITEM_FROM_LIST`
export const REMOVE_ALL_FROM_SEATED = `${MODULE_NAME}/REMOVE_ALL_FROM_SEATED`
