import { MODULE_NAME } from './constants'

export const INIT_TABLE_NUMBER = `${MODULE_NAME}/INIT_TABLE_NUMBER`
export const CHANGE_TABLE_NUMBER = `${MODULE_NAME}/CHANGE_TABLE_NUMBER`
export const CHANGE_CLOCK_STATE = `${MODULE_NAME}/CHANGE_CLOCK_STATE`
