import { MODULE_NAME } from './constants'

export const INIT_TABLE_NUMBER = `${MODULE_NAME}/INIT_TABLE_NUMBER`
export const CHANGE_TABLE_NUMBER = `${MODULE_NAME}/CHANGE_TABLE_NUMBER`

export const INIT_CLOCK_STATE = `${MODULE_NAME}/INIT_CLOCK_STATE`
export const CHANGE_CLOCK_STATE = `${MODULE_NAME}/CHANGE_CLOCK_STATE`

export const CHANGE_AUTO_SETTINGS = `${MODULE_NAME}/CHANGE_AUTO_SETTINGS`
export const CHANGE_DEFAULT_RECORD = `${MODULE_NAME}/CHANGE_DEFAULT_RECORD`

export const ADD_CLOCK_OUT_PLAYER = `${MODULE_NAME}/ADD_CLOCK_OUT_PLAYER`
export const REMOVE_CLOCK_OUT_PLAYER = `${MODULE_NAME}/REMOVE_CLOCK_OUT_PLAYER`
